In [1]:
import numpy as np
from sklearn import preprocessing
import pycasso
from sklearn.linear_model import lasso_path
from sklearn.linear_model import lars_path
from sklearn import linear_model
import time
import os

import pdb
from sklearn.metrics import accuracy_score

In [2]:
# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "pic")

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [3]:
def w_Initialization(d):
    w = 5*np.zeros((1,d))
    return w 

In [4]:
d = 2 
w = w_Initialization(d)

In [5]:
print(w)

[[0. 0.]]


In [6]:
print(w.shape)

(1, 2)


In [7]:
def sigmoid_activation(result):
    final_result = 1/(1 + np.exp(-result))
    return final_result 

In [9]:
# Generate X and Y
np.random.seed(1024)
cor_X = 0
S = cor_X * np.ones((d,d)) + (1 - cor_X) * np.diag(np.ones(d))
R = np.linalg.cholesky(S)

A = np.dot(np.random.normal(size = 2*2).reshape(2,2), R)
A = preprocessing.scale(A) * np.sqrt(float(d-1)/d)

In [10]:
S

array([[1., 0.],
       [0., 1.]])

In [11]:
A

array([[ 0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [74]:
b = np.array((1, 0))
b = b.reshape(2,1)

In [75]:
b

array([[1],
       [0]])

In [15]:
labd = np.sqrt(1/d)

In [16]:
w

array([[0., 0.]])

In [20]:
final_result = sigmoid_activation(np.dot(w, A.T))

In [21]:
final_result 

array([[0.5, 0.5]])

In [22]:
b_T = b.T

In [23]:
b

array([[ 1],
       [-1]])

In [24]:
b_T

array([[ 1, -1]])

In [25]:
b_T*np.log(final_result) 

array([[-0.69314718,  0.69314718]])

In [26]:
(1 - b_T)*np.log(final_result)

array([[-0.        , -1.38629436]])

In [28]:
np.log(final_result)

array([[-0.69314718, -0.69314718]])

In [29]:
1-b_T

array([[0, 2]])

In [30]:
(-1/2)*(np.sum((b_T*np.log(final_result)) + (1- b_T)*np.log(1-final_result)))

0.6931471805599453

In [32]:
labd*np.sqrt(np.linalg.norm(w))

0.0

In [33]:
final_result-b_T

array([[-0.5,  1.5]])

In [38]:
np.dot(A, (final_result - b_T).T)

array([[-1.41421356],
       [ 1.41421356]])

In [39]:
b 

array([[ 1],
       [-1]])

In [45]:
np.multiply(b,np.dot(A,w.T))

array([[ 0.],
       [-0.]])

In [48]:
cost = (1/d)*np.sum(np.log(1 + np.exp(np.dot(A,w.T))) - np.multiply(b,np.dot(A,w.T))) + labd * np.linalg.norm(w)

In [49]:
cost

0.6931471805599453

In [55]:
w = np.array((0.5, 0.3))

In [59]:
np.exp(np.dot(A,w.T))

array([1.15190991, 0.86812345])

In [64]:
np.dot(np.multiply(1./(1+np.exp(np.dot(A,w.T))), np.exp(np.dot(A,w.T))),A)

array([ 0.04991683, -0.04991683])

In [70]:
A[:,0].shape

(2,)

In [71]:
b.shape

(2, 1)

In [76]:
b

array([[1],
       [0]])

In [77]:
np.multiply(A[:,0],b)

array([[ 0.70710678, -0.70710678],
       [ 0.        , -0.        ]])

In [80]:
temp = np.multiply(1./(1+np.exp(np.dot(A,w.T))), np.exp(np.dot(A,w.T)))

In [81]:
temp

array([0.53529653, 0.46470347])

In [85]:
w

array([0.5, 0.3])

In [90]:
np.dot(A,w.T)

(2,)

In [83]:
1+np.exp(np.dot(A.T,w))

array([2.15190991, 1.86812345])

In [95]:
np.multiply( np.multiply(1./(1+np.exp(np.dot(A,w.T))), np.exp(np.dot(A,w.T))), A[0,:]) 

array([ 0.37851181, -0.32859497])

In [79]:
np.dot(A.T, b)

array([[ 0.70710678],
       [-0.70710678]])

In [ ]:
grad = (1/d)*np.sum(np.multiply(1./(1+np.exp(np.dot(A,w.T))), np.exp(np.dot(A,w.T))))